In [25]:
import pandas as pd
import numpy as np

In [26]:
movies = pd.read_csv('./data/movies.csv')
links = pd.read_csv('./data/links.csv')
tags = pd.read_csv('./data/tags.csv')
ratings = pd.read_csv('./data/ratings.csv')

In [27]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [28]:
movies.isna().sum() # No missing values

movieId    0
title      0
genres     0
dtype: int64

In [29]:
movies.duplicated().sum()  # No duplicates

np.int64(0)

In [30]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [31]:
# Replace pipe with space, then remove extra padding spaces
movies['genres'] = movies['genres'].str.replace('|', ' ', regex=False).str.strip()
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

In [32]:
links

      movieId   imdbId    tmdbId
0           1   114709     862.0
1           2   113497    8844.0
2           3   113228   15602.0
3           4   114885   31357.0
4           5   113041   11862.0
...       ...      ...       ...
9737   193581  5476944  432131.0
9738   193583  5914996  445030.0
9739   193585  6397426  479308.0
9740   193587  8391976  483455.0
9741   193609   101726   37891.0

[9742 rows x 3 columns]

In [33]:
links.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

In [34]:
# Converting tmdbID float to int
links['tmdbId'] = links['tmdbId'].astype('Int64')
display(links)
links.info()

      movieId   imdbId  tmdbId
0           1   114709     862
1           2   113497    8844
2           3   113228   15602
3           4   114885   31357
4           5   113041   11862
...       ...      ...     ...
9737   193581  5476944  432131
9738   193583  5914996  445030
9739   193585  6397426  479308
9740   193587  8391976  483455
9741   193609   101726   37891

[9742 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   Int64
dtypes: Int64(1), int64(2)
memory usage: 238.0 KB

In [35]:
# We don't need imdb as we can't do webscraping in imdb, but we can get info from tmdb 
links.drop('imdbId', axis=1, inplace=True)

In [36]:
links.isna().sum()  # 8 missing vals, we need to join movies & links tables/datasets We can manually add ids

movieId    0
tmdbId     8
dtype: int64

In [37]:
links[links.isna().any(axis=1)]

      movieId  tmdbId
624       791    <NA>
843      1107    <NA>
2141     2851    <NA>
3027     4051    <NA>
5532    26587    <NA>
5854    32600    <NA>
6059    40697    <NA>
7382    79299    <NA>

In [38]:
links.duplicated().sum()  # No duplicates

np.int64(0)

In [39]:
tags

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [40]:
# no need of timestamp col
tags.drop('timestamp', axis=1, inplace=True)

In [41]:
tags.isna().sum() # No missing values

userId     0
movieId    0
tag        0
dtype: int64

In [42]:
tags.duplicated().sum()  # No duplicates

np.int64(0)

In [43]:
tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   3683 non-null   int64
 1   movieId  3683 non-null   int64
 2   tag      3683 non-null   object
dtypes: int64(2), object(1)
memory usage: 86.4+ KB

In [44]:
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [45]:
# w need of timestamp col for sorting user rating which mimics real world data pattern
# ratings.drop('timestamp', axis=1, inplace=True)

In [46]:
ratings.isna().sum() # No missing values

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [47]:
ratings.duplicated().sum()  # No duplicates

np.int64(0)

In [48]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [49]:
ratings.describe()   # To know about ratings and to check its validity like whether its in correct range or not -- ITS correct

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [50]:
# adding movie titles to ratings based on movieId

### Need to combine movies and links dataset and use tmdbId to get movie info with api and add more details to the dataset

In [51]:
# Merge on common column 'movieId'
movies_df = pd.merge(movies, links, on='movieId', how='inner')
movies_df

,movieId,title,genres,tmdbId
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,862
1,2,Jumanji (1995),Adventure Children Fantasy,8844
2,3,Grumpier Old Men (1995),Comedy Romance,15602
3,4,Waiting to Exhale (1995),Comedy Drama Romance,31357
4,5,Father of the Bride Part II (1995),Comedy,11862
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,432131
9738,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,445030
9739,193585,Flint (2017),Drama,479308
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,483455
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,37891

In [52]:
movies_df[movies_df.isna().any(axis=1)]

,movieId,title,genres,tmdbId
624,791,"Last Klezmer: Leopold Kozlowski, His Life and ...",Documentary,<NA>
843,1107,Loser (1991),Comedy,<NA>
2141,2851,Saturn 3 (1980),Adventure Sci-Fi Thriller,<NA>
3027,4051,Horrors of Spider Island (Ein Toter Hing im Ne...,Horror Sci-Fi,<NA>
5532,26587,"Decalogue, The (Dekalog) (1989)",Crime Drama Romance,<NA>
5854,32600,Eros (2004),Drama,<NA>
6059,40697,Babylon 5,Sci-Fi,<NA>
7382,79299,"No. 1 Ladies' Detective Agency, The (2008)",Comedy Crime Mystery,<NA>

In [53]:
tmdb_fix = {
    "Saturn 3 (1980)": 19761,
    "Horrors of Spider Island (1960)": 24110,
    "Eros (2004)": 39850,
    "Babylon 5": 3137,
    "The No. 1 Ladies' Detective Agency (2008)": 20317,
    "Decalogue, The (Dekalog) (1989)": 42699
}

movies_df["tmdbId"] = movies_df["tmdbId"].fillna(
    movies_df["title"].map(tmdb_fix)
)

movies_df.isna().sum(), ratings.shape

(movieId    0
 title      0
 genres     0
 tmdbId     4
 dtype: int64,
 (100836, 4))

In [54]:
# Removing rest of unknown tmdbId records and also removing from ratings dataset also
rem_tmdb = movies_df[movies_df.isna().any(axis=1)]['movieId']
ratings = ratings[~ratings['movieId'].isin(rem_tmdb)]
movies_df.dropna(inplace=True)
movies_df.isna().sum(), ratings.shape

(movieId    0
 title      0
 genres     0
 tmdbId     0
 dtype: int64,
 (100831, 4))

### We want even tags to be also aggregated based on movieId and merge with movies_df

In [58]:
tags_grpd = tags.groupby('movieId')['tag'].agg(lambda x: ' '.join(x))
tags_grpd

movieId
1                                         pixar pixar fun
2            fantasy magic board game Robin Williams game
3                                               moldy old
5                                        pregnancy remake
7                                                  remake
                               ...
183611                        Comedy funny Rachel McAdams
184471    adventure Alicia Vikander video game adaptation
187593                  Josh Brolin Ryan Reynolds sarcasm
187595                            Emilia Clarke star wars
193565                      anime comedy gintama remaster
Name: tag, Length: 1572, dtype: object

In [59]:
movies_meta = pd.merge(movies_df, tags_grpd, on='movieId', how='left')
movies_meta

,movieId,title,genres,tmdbId,tag
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,862,pixar pixar fun
1,2,Jumanji (1995),Adventure Children Fantasy,8844,fantasy magic board game Robin Williams game
2,3,Grumpier Old Men (1995),Comedy Romance,15602,moldy old
3,4,Waiting to Exhale (1995),Comedy Drama Romance,31357,NaN
4,5,Father of the Bride Part II (1995),Comedy,11862,pregnancy remake
...,...,...,...,...,...
9733,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,432131,NaN
9734,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,445030,NaN
9735,193585,Flint (2017),Drama,479308,NaN
9736,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,483455,NaN
9737,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,37891,NaN

In [60]:
movies_meta.isna().sum()

movieId       0
title         0
genres        0
tmdbId        0
tag        8166
dtype: int64

In [61]:
a

NameError: name 'a' is not defined

In [ ]:
# movies_meta.fillna('', inplace=True)
# movies_meta.isna().sum()

In [ ]:
import requests
from tqdm import tqdm
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
# import logging

In [ ]:
API_KEY = "e0dd5e1df411ea273a7b3bdfd8d3df78"

def get_movie_details(tmdb_id, max_retries=3):
   
    url = f"https://api.themoviedb.org/3/movie/{tmdb_id}"
    params = {
        "api_key": API_KEY,
        "append_to_response": "credits"
    }
    
    # Try twice
    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=5)
            
            if response.status_code == 200:
                data = response.json()
                
                overview = data.get("overview", "")
                
                # Get Director
                director = ""
                for crew in data.get("credits", {}).get("crew", []):
                    if crew.get("job") == "Director":
                        director = crew.get("name", "")
                        break
                
                # Get Top 5 Actors
                cast = data.get("credits", {}).get("cast", [])
                actors = ", ".join([actor.get("name", "") for actor in cast[:5] if actor.get("name")])
                
                return overview, director, actors
            
            elif response.status_code == 404:
                return "", "", ""  # Movie doesn't exist
            
        except:
            if attempt == 0:  # First attempt failed, try once more
                time.sleep(0.5)
                continue
    
    return np.nan, np.nan, np.nan  # Both attempts failed


def get_movie_details_with_id(tmdb_id, max_retries=3):
    """Wrapper that returns tmdb_id with results"""
    overview, director, actors = get_movie_details(tmdb_id, max_retries)
    return tmdb_id, overview, director, actors

def super_fast_enrich_refetch(df, ind, num_threads=15, max_retries=3):
    
    results = []
    
    with ThreadPoolExecutor(max_workers=num_threads) as executor:
        futures = [executor.submit(get_movie_details_with_id, tmdb_id, max_retries) 
                  for tmdb_id in df.iloc[ind]["tmdbId"].tolist()]
        
        for future in tqdm(as_completed(futures), total=len(futures), desc="Fetching"):
            results.append(future.result())
    
    #display(results)    
    cols = ['tmdbId', 'overview', 'director', 'actors']
    df.loc[df.index[ind], cols] = results
    
    return df


def super_fast_enrich(df, num_threads=15, max_retries=3):
    
    results = []
    
    with ThreadPoolExecutor(max_workers=num_threads) as executor:
        futures = [executor.submit(get_movie_details_with_id, tmdb_id, max_retries) 
                  for tmdb_id in df["tmdbId"].tolist()]
        
        for future in tqdm(as_completed(futures), total=len(futures), desc="Fetching"):
            results.append(future.result())
    
    # Create results DataFrame
    results_df = pd.DataFrame(results, columns=['tmdbId', 'overview', 'director', 'actors'])
    
    # Drop old columns if they exist
    df = df.drop(columns=['overview', 'director', 'actors'], errors='ignore')
    
    # Merge
    df = df.merge(results_df, on='tmdbId', how='left')
    
    return df


# STEP 1: Load your data
# df = movies_meta.copy()

# # STEP 2: Enrich with retry logic (10 attempts per movie)
# df = super_fast_enrich(df, num_threads=20, max_retries=7)

# # Refetching if any missing vals
# ind = df[df['actors'].isna()].index.to_list()
# df = super_fast_enrich_refetch(df, ind, 20, 5)

# df

Fetching: 100%|██████████| 9738/9738 [18:28<00:00,  8.78it/s]
Fetching: 100%|██████████| 2/2 [00:01<00:00,  1.79it/s]

,movieId,title,genres,tmdbId,tag,overview,director,actors
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,862,pixar pixar fun,"Led by Woody, Andy's toys live happily in his ...",John Lasseter,"Tom Hanks, Tim Allen, Don Rickles, Jim Varney,..."
1,2,Jumanji (1995),Adventure Children Fantasy,8844,fantasy magic board game Robin Williams game,When siblings Judy and Peter discover an encha...,Joe Johnston,"Robin Williams, Kirsten Dunst, Bradley Pierce,..."
2,3,Grumpier Old Men (1995),Comedy Romance,15602,moldy old,A family wedding reignites the ancient feud be...,Howard Deutch,"Walter Matthau, Jack Lemmon, Ann-Margret, Soph..."
3,4,Waiting to Exhale (1995),Comedy Drama Romance,31357,NaN,"Cheated on, mistreated and stepped on, the wom...",Forest Whitaker,"Whitney Houston, Angela Bassett, Loretta Devin..."
4,5,Father of the Bride Part II (1995),Comedy,11862,pregnancy remake,Just when George Banks has recovered from his ...,Charles Shyer,"Steve Martin, Diane Keaton, Martin Short, Kimb..."
...,...,...,...,...,...,...,...,...
9741,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,432131,NaN,"Ciel learns of a ""Aurora Society"", that is rum...",Noriyuki Abe,"Daisuke Ono, Maaya Sakamoto, Yukari Tamura, Ju..."
9742,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,445030,NaN,Six thousand years before Sora and Shiro were ...,Atsuko Ishizuka,"Yoko Hikasa, Ai Kayano, Yoshitsugu Matsuoka, K..."
9743,193585,Flint (2017),Drama,479308,NaN,A woman deals with the toxic water scandal in ...,Bruce Beresford,"Queen Latifah, Betsy Brandt, Rob Morrow, Marin..."
9744,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,483455,NaN,A large scale catastrophe is occurring across ...,Takuya Igarashi,"Kensho Ono, Mamoru Miyano, Kisho Taniyama, Yut..."
9745,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,37891,NaN,"Outrageous, misogynistic and vulgar-to-the-max...",Jay Dubin,"Andrew Dice Clay, Eddie Griffin, Sylvia Harman..."

In [ ]:
df.isna().sum() # No na values, but some have empty vals

movieId        0
title          0
genres         0
tmdbId         0
tag         8173
overview       0
director       0
actors         0
dtype: int64

In [ ]:
df[df['overview'] == '']['tmdbId']  # Empty vals - '' - For these movies we will be just using tags, genres etc. Not going to remove

3125     12773
3360     17882
3678     68149
3739     24549
4980     14980
         ...
9638    463612
9655    106035
9659    363444
9694    502892
9706    500609
Name: tmdbId, Length: 115, dtype: Int64

In [ ]:
get_movie_details(12773, 7)

('', '', '')

In [62]:
# Also adding title to ratings dataset
ratings_title = pd.merge(ratings, movies_meta[['movieId', 'title', 'tmdbId']], on='movieId', how='left')
ratings_title

,userId,movieId,rating,timestamp,title,tmdbId
0,1,1,4.0,964982703,Toy Story (1995),862
1,1,3,4.0,964981247,Grumpier Old Men (1995),15602
2,1,6,4.0,964982224,Heat (1995),949
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),807
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",629
...,...,...,...,...,...,...
100826,610,166534,4.0,1493848402,Split (2017),381288
100827,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),324552
100828,610,168250,5.0,1494273047,Get Out (2017),419430
100829,610,168252,5.0,1493846352,Logan (2017),263115
100830,610,170875,3.0,1493846415,The Fate of the Furious (2017),337339

### Data cleaning is done, now need to convert to cleaned csv files

In [ ]:
# df.to_csv("./data/movie_tags_cleaned.csv", index=False)
# ratings_title.to_csv("./data/ratings_cleaned.csv", index=False)

In [ ]:
# x = [1, 3, 5]
# y = [4000, 640, 121]
# df = pd.DataFrame({'x_axis': x, 'y_axis': y})

# # Plot y against x
# df.plot(x='x_axis', y='y_axis', kind='line', marker='o')

In [ ]:

# coefficients = np.polyfit(x, y, 2)
# p = np.poly1d(coefficients) 
# # p is now your function: y = ax^2 + bx + c

# # 2. Find where y = 0 (Roots)
# roots = p.roots
# # Filter for real numbers only
# real_roots = roots[np.isreal(roots)].real

# print(f"The x-value where y reaches 0 is approximately: {real_roots}")

In [ ]:
# ratings = pd.read_csv('./data/ratings_cleaned.csv')
# movies = pd.read_csv('./data/movie_tags_cleaned.csv')

In [ ]:
ratings.head()

   userId  movieId  rating                        title  tmdbId
0       1        1     4.0             Toy Story (1995)     862
1       1        3     4.0      Grumpier Old Men (1995)   15602
2       1        6     4.0                  Heat (1995)     949
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)     807
4       1       50     5.0   Usual Suspects, The (1995)     629

In [ ]:
movies.head()

,movieId,title,genres,tmdbId,tag,overview,director,actors
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,862,pixar pixar fun,"Led by Woody, Andy's toys live happily in his ...",John Lasseter,"Tom Hanks, Tim Allen, Don Rickles, Jim Varney,..."
1,2,Jumanji (1995),Adventure Children Fantasy,8844,fantasy magic board game Robin Williams game,When siblings Judy and Peter discover an encha...,Joe Johnston,"Robin Williams, Kirsten Dunst, Bradley Pierce,..."
2,3,Grumpier Old Men (1995),Comedy Romance,15602,moldy old,A family wedding reignites the ancient feud be...,Howard Deutch,"Walter Matthau, Jack Lemmon, Ann-Margret, Soph..."
3,4,Waiting to Exhale (1995),Comedy Drama Romance,31357,NaN,"Cheated on, mistreated and stepped on, the wom...",Forest Whitaker,"Whitney Houston, Angela Bassett, Loretta Devin..."
4,5,Father of the Bride Part II (1995),Comedy,11862,pregnancy remake,Just when George Banks has recovered from his ...,Charles Shyer,"Steve Martin, Diane Keaton, Martin Short, Kimb..."

In [ ]:
movies.isna().sum()

movieId        0
title          0
genres         0
tmdbId         0
tag         8173
overview     115
director     118
actors       147
dtype: int64

In [64]:
ratings[['movieId', 'rating']].groupby('movieId').mean()

           rating
movieId
1        3.920930
2        3.431818
3        3.259615
4        2.357143
5        3.071429
...           ...
193581   4.000000
193583   3.500000
193585   3.500000
193587   3.500000
193609   4.000000

[9720 rows x 1 columns]

In [65]:
# Also going to add avg_rating & vote count for each movies
avg_rating = ratings[['movieId', 'rating']].groupby('movieId').mean()
count_rating = ratings[['movieId', 'rating']].groupby('movieId').count()
# merging with movies
movies = pd.merge(movies, avg_rating, on='movieId', how='left',)
movies = pd.merge(movies, count_rating, on='movieId', how='left')
movies.rename(columns={'rating_x':'avg_rating', 'rating_y':'count_rating'}, inplace=True)
movies['count_rating'] = movies['count_rating'].astype('Int64')
movies

,movieId,title,genres,avg_rating,count_rating
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,3.920930,215
1,2,Jumanji (1995),Adventure Children Fantasy,3.431818,110
2,3,Grumpier Old Men (1995),Comedy Romance,3.259615,52
3,4,Waiting to Exhale (1995),Comedy Drama Romance,2.357143,7
4,5,Father of the Bride Part II (1995),Comedy,3.071429,49
...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,4.000000,1
9738,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,3.500000,1
9739,193585,Flint (2017),Drama,3.500000,1
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,3.500000,1
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,4.000000,1

In [ ]:
movies.isna().sum()

movieId            0
title              0
genres             0
tmdbId             0
tag             8173
overview         115
director         118
actors           147
avg_rating        18
count_rating      18
dtype: int64

In [ ]:
count_rating.shape, avg_rating.shape, movies.shape

((9720, 1), (9720, 1), (9746, 10))

In [ ]:
a

In [ ]:
# There are few movies which are not even rated yet, so we need to fillna(0)
movies[['avg_rating', 'count_rating']] = movies[['avg_rating', 'count_rating']].fillna(0)
movies.isna().sum()

movieId            0
title              0
genres             0
tmdbId             0
tag             8173
overview         115
director         118
actors           147
avg_rating         0
count_rating       0
dtype: int64

In [ ]:
movies

,movieId,title,genres,tmdbId,tag,overview,director,actors,avg_rating,count_rating
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,862,pixar pixar fun,"Led by Woody, Andy's toys live happily in his ...",John Lasseter,"Tom Hanks, Tim Allen, Don Rickles, Jim Varney,...",3.920930,215
1,2,Jumanji (1995),Adventure Children Fantasy,8844,fantasy magic board game Robin Williams game,When siblings Judy and Peter discover an encha...,Joe Johnston,"Robin Williams, Kirsten Dunst, Bradley Pierce,...",3.431818,110
2,3,Grumpier Old Men (1995),Comedy Romance,15602,moldy old,A family wedding reignites the ancient feud be...,Howard Deutch,"Walter Matthau, Jack Lemmon, Ann-Margret, Soph...",3.259615,52
3,4,Waiting to Exhale (1995),Comedy Drama Romance,31357,NaN,"Cheated on, mistreated and stepped on, the wom...",Forest Whitaker,"Whitney Houston, Angela Bassett, Loretta Devin...",2.357143,7
4,5,Father of the Bride Part II (1995),Comedy,11862,pregnancy remake,Just when George Banks has recovered from his ...,Charles Shyer,"Steve Martin, Diane Keaton, Martin Short, Kimb...",3.071429,49
...,...,...,...,...,...,...,...,...,...,...
9741,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,432131,NaN,"Ciel learns of a ""Aurora Society"", that is rum...",Noriyuki Abe,"Daisuke Ono, Maaya Sakamoto, Yukari Tamura, Ju...",4.000000,1
9742,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,445030,NaN,Six thousand years before Sora and Shiro were ...,Atsuko Ishizuka,"Yoko Hikasa, Ai Kayano, Yoshitsugu Matsuoka, K...",3.500000,1
9743,193585,Flint (2017),Drama,479308,NaN,A woman deals with the toxic water scandal in ...,Bruce Beresford,"Queen Latifah, Betsy Brandt, Rob Morrow, Marin...",3.500000,1
9744,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,483455,NaN,A large scale catastrophe is occurring across ...,Takuya Igarashi,"Kensho Ono, Mamoru Miyano, Kisho Taniyama, Yut...",3.500000,1
9745,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,37891,NaN,"Outrageous, misogynistic and vulgar-to-the-max...",Jay Dubin,"Andrew Dice Clay, Eddie Griffin, Sylvia Harman...",4.000000,1

In [66]:
ratings

,userId,movieId,rating,timestamp,title,tmdbId
0,1,1,4.0,964982703,Toy Story (1995),862
1,1,3,4.0,964981247,Grumpier Old Men (1995),15602
2,1,6,4.0,964982224,Heat (1995),949
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),807
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",629
...,...,...,...,...,...,...
100826,610,166534,4.0,1493848402,Split (2017),381288
100827,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),324552
100828,610,168250,5.0,1494273047,Get Out (2017),419430
100829,610,168252,5.0,1493846352,Logan (2017),263115
100830,610,170875,3.0,1493846415,The Fate of the Furious (2017),337339

In [ ]:
# import pandas as pd

# ratings = pd.read_csv('./data/ratings_cleaned.csv')
# ratings

        userId  movieId                           title  tmdbId  rating
0            1        1                Toy Story (1995)     862     4.0
1            1        3         Grumpier Old Men (1995)   15602     4.0
2            1        6                     Heat (1995)     949     4.0
3            1       47     Seven (a.k.a. Se7en) (1995)     807     5.0
4            1       50      Usual Suspects, The (1995)     629     5.0
...        ...      ...                             ...     ...     ...
100826     610   166534                    Split (2017)  381288     4.0
100827     610   168248   John Wick: Chapter Two (2017)  324552     5.0
100828     610   168250                  Get Out (2017)  419430     5.0
100829     610   168252                    Logan (2017)  263115     5.0
100830     610   170875  The Fate of the Furious (2017)  337339     3.0

[100831 rows x 5 columns]

In [69]:
ratings.groupby(['userId', 'movieId'], as_index=False).agg(
    rating=('rating', 'mean'),       # Take the average of the ratings
    timestamp=('timestamp', 'max')   # Take the most recent timestamp
)

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100826     610   166534     4.0  1493848402
100827     610   168248     5.0  1493850091
100828     610   168250     5.0  1494273047
100829     610   168252     5.0  1493846352
100830     610   170875     3.0  1493846415

[100831 rows x 4 columns]

In [70]:
# Removing duplicate/multiple ratings of each user by taking their avg rating
ratings = ratings.groupby(['userId', 'movieId', 'title', 'tmdbId'], as_index=False).agg(
    rating=('rating', 'mean'),       # Take the average of the ratings
    timestamp=('timestamp', 'max')   # Take the most recent timestamp
)
ratings

,userId,movieId,title,tmdbId,rating,timestamp
0,1,1,Toy Story (1995),862,4.0,964982703
1,1,3,Grumpier Old Men (1995),15602,4.0,964981247
2,1,6,Heat (1995),949,4.0,964982224
3,1,47,Seven (a.k.a. Se7en) (1995),807,5.0,964983815
4,1,50,"Usual Suspects, The (1995)",629,5.0,964982931
...,...,...,...,...,...,...
100826,610,166534,Split (2017),381288,4.0,1493848402
100827,610,168248,John Wick: Chapter Two (2017),324552,5.0,1493850091
100828,610,168250,Get Out (2017),419430,5.0,1494273047
100829,610,168252,Logan (2017),263115,5.0,1493846352
100830,610,170875,The Fate of the Furious (2017),337339,3.0,1493846415

In [71]:
ratings = ratings.sort_values(by=['userId', 'timestamp']).reset_index(drop=True)
ratings

,userId,movieId,title,tmdbId,rating,timestamp
0,1,804,She's the One (1996),11363,4.0,964980499
1,1,1210,Star Wars: Episode VI - Return of the Jedi (1983),1892,5.0,964980499
2,1,2018,Bambi (1942),3170,5.0,964980523
3,1,2628,Star Wars: Episode I - The Phantom Menace (1999),1893,4.0,964980523
4,1,2826,"13th Warrior, The (1999)",1911,4.0,964980523
...,...,...,...,...,...,...
100826,610,101739,Evil Dead (2013),109428,3.5,1495959269
100827,610,70,From Dusk Till Dawn (1996),755,4.0,1495959282
100828,610,328,Tales from the Crypt Presents: Demon Knight (1...,9059,3.5,1495959299
100829,610,2459,"Texas Chainsaw Massacre, The (1974)",30497,3.5,1495959405
100830,610,3917,Hellraiser (1987),9003,4.0,1495959411

In [ ]:
# Cleaned data
# movies.to_csv("./data/movie_tags_cleaned.csv", index=False)
# ratings.to_csv("./data/ratings_cleaned.csv", index=False)